### ISSUE TITLE
Last version v0.0.72 slice out of range error

### ISSUE THREAD

**Issue by javi11** [javi11/usenet-drive#77]
In the last version some nzb are returning the given error

`panic: runtime error: slice bounds out of range [-1:]
goroutine 474 [running]:
github.com/mnightingale/rapidyenc.(*Decoder).Transform(0xc0002465a0, {0xc002af3000, 0x1000, 0x1000}, {0xc000172000, 0x2c, 0x1000}, 0x0)
	/go/pkg/mod/github.com/mnightingale/rapidyenc@v0.0.0-20231127201145-8792729266a1/decoder.go:206 +0x915
github.com/mnightingale/rapidyenc.(*Decoder).Read(0xc0002465a0, {0xc0045651b0, 0x20e50, 0xc0002465a0?})
	/go/pkg/mod/github.com/mnightingale/rapidyenc@v0.0.0-20231127201145-8792729266a1/decoder.go:142 +0x173
io.ReadAll({0xd274e0, 0xc0002465a0})
	/usr/local/go/src/io/io.go:704 +0x7e
github.com/javi11/usenet-drive/internal/usenet/filereader.(*buffer).downloadSegment.func1()
	/app/internal/usenet/filereader/buffer.go:294 +0x5da
github.com/avast/retry-go.Do(0xc002855d78, {0xc000086d10, 0x5, 0x413505?})
	/go/pkg/mod/github.com/avast/retry-go@v3.0.0+incompatible/retry.go:127 +0x1c3
github.com/javi11/usenet-drive/internal/usenet/filereader.(*buffer).downloadSegment(0xc00020ebe0, {0xd2bb78?, 0xc00012a870}, {{{0xc0000b6750, 0x23}, {0xc003bfcf60, 0x7}}, 0xb71b0, 0x2, {0xc0000b67b0, ...}}, ...)
	/app/internal/usenet/filereader/buffer.go:259 +0x42a
github.com/javi11/usenet-drive/internal/usenet/filereader.(*buffer).downloadBoost(0xc00020ebe0, {0xd2bb78, 0xc00012a870})
	/app/internal/usenet/filereader/buffer.go:365 +0x1d4
github.com/javi11/usenet-drive/internal/usenet/filereader.NewBuffer.func1()
	/app/internal/usenet/filereader/buffer.go:88 +0x58
created by github.com/javi11/usenet-drive/internal/usenet/filereader.NewBuffer in goroutine 302
	/app/internal/usenet/filereader/buffer.go:86 +0x2ac
`

**Comment by javi11** [comment]
Fixed on version V0.0.75 https://github.com/mnightingale/rapidyenc/pull/4
